# yaml for ci pipeline for github actions
name: CI-Pipeline

on:
  push:
    branches:
      - karsajobs

jobs:
  docker-image-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
